# Generated by Django 5.2 on 2025-05-06 17:18

import app.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('idade', models.PositiveIntegerField(blank=True, null=True)),
                ('is_gestor', models.BooleanField(default=False)),
                ('is_professor', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                
                ('NI', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('data_contratacao', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('PBE', 'Programação Back-end'), ('PWFE', 'Programação web front-end'), ('BCD', 'Banco de dados'), ('LIMA', 'Linguagem de marcação'), ('PRO', 'Projetos'), ('ELEB', 'Eletricidade Básica'), ('ELET', 'Eletrônica Analógica'), ('EDIG', 'Eletrônica Digital'), ('AUT', 'Automação Industrial'), ('INST', 'Instalações Elétricas'), ('ROBO', 'Robótica'), ('ECL', 'Circuitos Elétricos'), ('PLCL', 'Controladores Lógicos Programáveis'), ('MOTO', 'Máquinas e Motores Elétricos'), ('DESM', 'Desenho Mecânico'), ('MET', 'Metrologia'), ('MATE', 'Materiais de Engenharia'), ('MECG', 'Mecânica Geral'), ('SOLD', 'Soldagem'), ('FRES', 'Fresagem e Tornearia'), ('CNC', 'Comandos Numéricos Computadorizados'), ('CAD', 'Desenho Assistido por Computador (CAD)')], max_length=4)),
                ('curso', models.CharField(choices=[('CAD', 'MECATRONICA'), ('DS', 'DESENVOLVIMENTO DE SISTEMAS'), ('CAI', 'ELETRICA')], max_length=4)),
                ('carga_horaria', models.PositiveIntegerField(blank=True, null=True)),
                ('descricao', models.TextField(max_length=500)),
                ('professor_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Reservar_de_Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(validators=[app.models.Reservar_de_Ambiente.validador])),
                ('data_termino', models.DateField(validators=[app.models.Reservar_de_Ambiente.validador])),
                ('periodo', models.CharField(blank=True, choices=[('AM', 'Manhã'), ('PM', 'Tarde'), ('NI', 'Noturno')], max_length=2, null=True)),
                ('sala_reservado', models.CharField(blank=True, max_length=30, null=True)),
                ('disciplina_associada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina')),
                ('professor_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.professor')),
            ],
        ),
    ]
