# Generated by Django 5.2 on 2025-05-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_professor_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='usuario',
            new_name='user',
        ),
    ]
